#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# on the 9th iteration, it displays "Hi"
i=1

while [ $i -lt "10" ]
do
    echo "Best School"

    if [ $i -eq "9" ]
    then
        echo "Hi"

    fi

    ((i += 1))
done