#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# on the 9th iteration, it displays "Hi"
i="0"
while [ $i -lt 10 ]; do
		echo "Best School"
		i=$((i+1))
		if [ $i == 9 ]; then echo Hi; fi
done
